
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'de_demo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'de_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths:
    - de_demo/apps/events/dbt/models

clean-targets:         # directories to be removed by `dbt clean`
  - "dbt/target"
  - "dbt/logs"
  - "dbt_packages"


models:
    +on_schema_change: "sync_all_columns"
    +materialized: "ephemeral"
