include:
    - docker-compose.warehouse.yml

services:
  metabase:
    build:
      context: ..
      dockerfile: ./docker/metabase.dockerfile
    environment:
      - JAVA_OPTS=-Xms1g -Xmx2g
    ports:
      - '127.0.0.1:13001:3000'
    restart: always
    healthcheck:
      test: curl http://127.0.0.1:3000/api/health | grep '{"status":"ok"}'
      start_period: 30s
      interval: 5s
      timeout: 2s
      retries: 5
    logging:
      options:
        max-size: 50m
        max-file: 10

  metabase-migrator:
    image: de-demo-app:latest
    build:
      context: ..
      dockerfile: ./docker/de-demo.dockerfile
      target: app
    depends_on:
      metabase:
        condition: service_healthy
    command:
      - migrate
      - metabase
      - --addr=http://metabase:3000/
      - --db_host=ch
      - --db_port=8123
    logging:
      options:
        max-size: 50m
        max-file: 10
