include:
    - docker-compose.warehouse.yml

services:
  migrator:
    image: de-demo:latest
    build:
      context: ..
      dockerfile: ./docker/de-demo.dockerfile
    depends_on:
      ch:
        condition: service_healthy
    command:
      - migrate
      - clickhouse
      - --addr=http://ch:8123
    logging:
      options:
        max-size: 50m
        max-file: 10
