services:
  prometheus:
    image: prom/prometheus:v2.38.0
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '127.0.0.1:19090:9090'
    restart: always

  grafana:
    image: grafana/grafana:9.1.1
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/datasources/demo.yaml:/etc/grafana/provisioning/datasources/demo.yaml
      - ./grafana/provisioning/dashboards/demo.yaml:/etc/grafana/provisioning/dashboards/demo.yaml
      - ./grafana/demo_dashboard.json:/var/lib/grafana/dashboards/demo_dashboard.json
    ports:
      - '127.0.0.1:13000:3000'
    restart: always

volumes:
  prometheus:
  grafana:
