include:
    - docker-compose.warehouse.yml
    - docker-compose.monitoring.yml
    - docker-compose.bi.yml

services:
  api:
    image: de-demo:latest
    build:
      context: ..
      dockerfile: ./docker/de-demo.dockerfile
    ports:
      - '127.0.0.1:${DD__API__PORT:-18000}:8000'
    restart: always
    depends_on:
      ch:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      - DD__WAREHOUSE__CLICKHOUSE__ADDR=http://ch:8123
    command:
      - run
      - api
      - --host=0.0.0.0
      - --port=8000
      - --access_log=False
    logging:
      options:
        max-size: 50m
        max-file: 10
