global:
  scrape_interval: 1s

scrape_configs:
  - job_name: api
    static_configs:
      - targets:
          - 'api:8000'
        labels:
          service: de_demo
  - job_name: clickhouse
    static_configs:
      - targets:
          - 'ch:9363'
        labels:
          service: clickhouse